### PR TITLE
Add documentation on "header API"

### PR DESCRIPTION
**Pull request by claudiobizzotto**
See demo [here](http://it.claudiobizzotto.com/libpe-sphinx/).

### CODE REVIEW

**Comment by merces** [comment]
Nice! Thank you!

**Comment by claudiobizzotto** [comment]
:metal:

**Comment by jweyrich** [comment]
@claudiobizzotto the submodule introduced for sphinx_rtd_theme broke pev's build because the referenced commit no longer existed in the upstream repository. I needed to pick another reference (opted for branch/tag `rc-0.1.9`) to make it work again - hopefully. The thing is that I'm not sure it won't cease to exist at some point, and AFAIK, we're unable to reference a tag from a submodule, so we have 2 options: 1) Fork the referenced repository and link the submodule to our fork, effectively giving us full control of what ceases to exist or not, or 2) Incorporate the code into our own repository (which sounds like an overkill); Not sure which is "less-worse".

**Comment by claudiobizzotto** [comment]
Sorry for taking so long to reply, @jweyrich. Have you guys already made any decision or are you still considering those two options?

[So Sphinx RTD is not using tags on their releases? :slightly_frowning_face: In any case, I'll check their repo this week/weekend and see if there's another option]

**Pull request merged**
